In [58]:
import cbor
import matplotlib.pyplot as plt
import numpy as np
import re
import pandas as pd
import os

In [60]:
path = "/Users/hazelwat/Desktop/DSR/portfolio/DRS28_Hazel_n_Igor_portfolio_project/Data_for_Tests/20211202/Air_day/"
file_name = "Ambient.M01.cbor"
path_file = path + file_name

f_02 = open(path_file, 'rb')
obj = cbor.load(f_02) #dict

obj.keys()
# Out[16]: dict_keys(['protected', 'signature', 'payload'])

obj['payload']
obj['payload'].keys()
# dict_keys(['device_name', 'device_type', 'interval_ms', 'sensors', 'values'])

obj['payload']["sensors"]
# Out[22]: 
# [{'name': 'NO2', 'units': 'ppm'},
#  {'name': 'C2H5CH', 'units': 'ppm'},
#  {'name': 'VOC', 'units': 'ppm'},
#  {'name': 'CO', 'units': 'ppm'}]

d_01 = obj['payload']['values']
# Out[24]: 
# [[870.0, 542.0, 834.0, 582.0],
#  [870.0, 542.0, 834.0, 582.0],...

In [61]:
air_day = (obj['payload']['values'])

In [62]:
air_day

[[870.0, 542.0, 834.0, 582.0],
 [870.0, 542.0, 834.0, 582.0],
 [870.0, 542.0, 835.0, 582.0],
 [871.0, 542.0, 834.0, 582.0],
 [870.0, 542.0, 834.0, 583.0],
 [871.0, 543.0, 834.0, 582.0],
 [870.0, 542.0, 834.0, 581.0],
 [871.0, 543.0, 834.0, 583.0],
 [870.0, 542.0, 835.0, 582.0],
 [871.0, 543.0, 834.0, 582.0],
 [870.0, 543.0, 833.0, 581.0],
 [870.0, 542.0, 834.0, 583.0],
 [870.0, 543.0, 834.0, 581.0],
 [870.0, 543.0, 834.0, 583.0],
 [871.0, 542.0, 835.0, 582.0],
 [871.0, 543.0, 834.0, 582.0],
 [870.0, 543.0, 835.0, 583.0],
 [871.0, 542.0, 835.0, 582.0],
 [871.0, 542.0, 835.0, 582.0],
 [871.0, 543.0, 834.0, 583.0],
 [870.0, 542.0, 835.0, 582.0],
 [871.0, 542.0, 834.0, 583.0],
 [870.0, 542.0, 834.0, 583.0],
 [871.0, 543.0, 835.0, 582.0],
 [870.0, 542.0, 834.0, 582.0],
 [871.0, 542.0, 835.0, 583.0],
 [870.0, 543.0, 835.0, 582.0],
 [870.0, 543.0, 835.0, 582.0],
 [870.0, 543.0, 835.0, 582.0],
 [870.0, 542.0, 834.0, 582.0],
 [870.0, 543.0, 835.0, 582.0],
 [871.0, 543.0, 835.0, 582.0],
 [871.0,

In [64]:
len(air_day)

1000

In [65]:
air_day_mean= np.mean(air_day, axis=0)
print(air_day_mean)

[876.013 549.343 841.496 588.688]


### Air night

In [75]:
path2 = "/Users/hazelwat/Desktop/DSR/portfolio/DRS28_Hazel_n_Igor_portfolio_project/Data_for_Tests/20211202/Air_night/"
file_name2 = "Ambient3.N01.cbor"
path_file2 = path2 + file_name2

f_02 = open(path_file2, 'rb')
obj = cbor.load(f_02) #dict

obj.keys()
# Out[16]: dict_keys(['protected', 'signature', 'payload'])

obj['payload']
obj['payload'].keys()
# dict_keys(['device_name', 'device_type', 'interval_ms', 'sensors', 'values'])

obj['payload']["sensors"]
# Out[22]: 
# [{'name': 'NO2', 'units': 'ppm'},
#  {'name': 'C2H5CH', 'units': 'ppm'},
#  {'name': 'VOC', 'units': 'ppm'},
#  {'name': 'CO', 'units': 'ppm'}]

d_01 = obj['payload']['values']
# Out[24]: 
# [[870.0, 542.0, 834.0, 582.0],
#  [870.0, 542.0, 834.0, 582.0],...

In [76]:
air_night = (obj['payload']['values'])

In [77]:
air_night

[[612.0, 98.0, 389.0, 188.0],
 [612.0, 98.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 189.0],
 [611.0, 99.0, 390.0, 188.0],
 [612.0, 99.0, 390.0, 189.0],
 [612.0, 98.0, 390.0, 188.0],
 [612.0, 99.0, 390.0, 188.0],
 [611.0, 98.0, 390.0, 188.0],
 [612.0, 99.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 189.0],
 [612.0, 99.0, 391.0, 189.0],
 [612.0, 98.0, 390.0, 189.0],
 [611.0, 98.0, 390.0, 187.0],
 [612.0, 98.0, 391.0, 189.0],
 [612.0, 98.0, 391.0, 189.0],
 [612.0, 98.0, 391.0, 189.0],
 [611.0, 98.0, 391.0, 189.0],
 [612.0, 99.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 188.0],
 [612.0, 99.0, 391.0, 189.0],
 [611.0, 98.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 188.0],
 [612.0, 99.0, 390.0, 188.0],
 [612.0, 99.0, 391.0, 188.0],
 [611.0, 98.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 189.0],
 [612.0, 99.0, 390.0, 188.0],
 [612.0, 98.0, 391.0, 189.0],
 [612.0, 99.0, 390.0, 188.0],
 [612.0, 98.0, 390.0, 188.0],
 [612.0, 99.0, 390.0, 188.0],
 [612.0, 99.0, 390.0, 189.0],
 [612.0, 9

In [78]:
air_night_mean= np.mean(air_night, axis=0)
print(air_night_mean)

[608.995  98.75  390.818 187.602]


In [79]:
diff = air_day_mean - air_night_mean
print(diff)

[267.018 450.593 450.678 401.086]
