In [17]:
import cbor
import matplotlib.pyplot as plt
import numpy as np
import re
import pandas as pd
import os

In [18]:
path2 = "/Users/hazelwat/Desktop/DSR/portfolio/DRS28_Hazel_n_Igor_portfolio_project/Data_for_Tests/20211202/Coffee_day/"
file_name2 = "Coffee.M01.cbor"
path_file2 = path2 + file_name2

f_02 = open(path_file2, 'rb')
obj = cbor.load(f_02) #dict

obj.keys()
# Out[16]: dict_keys(['protected', 'signature', 'payload'])

obj['payload']
obj['payload'].keys()
# dict_keys(['device_name', 'device_type', 'interval_ms', 'sensors', 'values'])

obj['payload']["sensors"]
# Out[22]: 
# [{'name': 'NO2', 'units': 'ppm'},
#  {'name': 'C2H5CH', 'units': 'ppm'},
#  {'name': 'VOC', 'units': 'ppm'},
#  {'name': 'CO', 'units': 'ppm'}]

d_01 = obj['payload']['values']
# Out[24]: 
# [[870.0, 542.0, 834.0, 582.0],
#  [870.0, 542.0, 834.0, 582.0],...

In [19]:
coffee_day = (obj['payload']['values'])

In [20]:
coffee_day

[[890.0, 933.0, 808.0, 624.0],
 [891.0, 934.0, 807.0, 625.0],
 [891.0, 933.0, 808.0, 625.0],
 [891.0, 934.0, 808.0, 624.0],
 [891.0, 934.0, 807.0, 623.0],
 [891.0, 934.0, 807.0, 625.0],
 [891.0, 933.0, 807.0, 624.0],
 [891.0, 933.0, 808.0, 624.0],
 [891.0, 933.0, 806.0, 624.0],
 [891.0, 933.0, 807.0, 624.0],
 [891.0, 934.0, 808.0, 624.0],
 [891.0, 933.0, 808.0, 624.0],
 [890.0, 933.0, 807.0, 625.0],
 [891.0, 934.0, 807.0, 624.0],
 [891.0, 933.0, 807.0, 624.0],
 [891.0, 934.0, 807.0, 624.0],
 [890.0, 933.0, 808.0, 624.0],
 [890.0, 933.0, 807.0, 623.0],
 [891.0, 934.0, 807.0, 624.0],
 [891.0, 934.0, 808.0, 623.0],
 [892.0, 934.0, 807.0, 623.0],
 [890.0, 934.0, 807.0, 623.0],
 [891.0, 934.0, 807.0, 624.0],
 [890.0, 933.0, 807.0, 624.0],
 [891.0, 934.0, 807.0, 624.0],
 [891.0, 933.0, 808.0, 624.0],
 [890.0, 934.0, 808.0, 625.0],
 [891.0, 934.0, 807.0, 624.0],
 [891.0, 933.0, 808.0, 624.0],
 [892.0, 934.0, 807.0, 624.0],
 [890.0, 934.0, 807.0, 624.0],
 [890.0, 934.0, 808.0, 623.0],
 [890.0,

In [21]:
len(coffee_day)

1000

In [22]:
coffee_day_mean= np.mean(coffee_day, axis=0)
print(coffee_day_mean)

[890.699 933.645 806.182 619.311]


In [23]:
air_day_mean = [876.013, 549.343, 841.496, 588.688]

In [24]:
diff_day= coffee_day_mean - air_day_mean
print(diff_day)

[ 14.686 384.302 -35.314  30.623]


### Coffee Night

In [25]:
path2 = "/Users/hazelwat/Desktop/DSR/portfolio/DRS28_Hazel_n_Igor_portfolio_project/Data_for_Tests/20211202/Coffee_night/"
file_name2 = "Coffee_powder.N01.cbor"
path_file2 = path2 + file_name2

f_02 = open(path_file2, 'rb')
obj = cbor.load(f_02) #dict

obj.keys()
# Out[16]: dict_keys(['protected', 'signature', 'payload'])

obj['payload']
obj['payload'].keys()
# dict_keys(['device_name', 'device_type', 'interval_ms', 'sensors', 'values'])

obj['payload']["sensors"]
# Out[22]: 
# [{'name': 'NO2', 'units': 'ppm'},
#  {'name': 'C2H5CH', 'units': 'ppm'},
#  {'name': 'VOC', 'units': 'ppm'},
#  {'name': 'CO', 'units': 'ppm'}]

d_01 = obj['payload']['values']
# Out[24]: 
# [[870.0, 542.0, 834.0, 582.0],
#  [870.0, 542.0, 834.0, 582.0],...

In [26]:
coffee_night = (obj['payload']['values'])

In [27]:
coffee_night

[[855.0, 806.0, 741.0, 535.0],
 [856.0, 806.0, 740.0, 535.0],
 [856.0, 807.0, 741.0, 535.0],
 [856.0, 806.0, 741.0, 535.0],
 [856.0, 806.0, 740.0, 535.0],
 [855.0, 807.0, 742.0, 535.0],
 [856.0, 807.0, 742.0, 537.0],
 [856.0, 807.0, 741.0, 535.0],
 [856.0, 807.0, 741.0, 536.0],
 [856.0, 807.0, 742.0, 536.0],
 [856.0, 807.0, 742.0, 536.0],
 [856.0, 807.0, 742.0, 537.0],
 [856.0, 807.0, 741.0, 537.0],
 [856.0, 807.0, 741.0, 537.0],
 [857.0, 808.0, 741.0, 537.0],
 [857.0, 808.0, 741.0, 537.0],
 [857.0, 808.0, 742.0, 538.0],
 [857.0, 809.0, 742.0, 537.0],
 [857.0, 808.0, 742.0, 537.0],
 [858.0, 809.0, 742.0, 537.0],
 [857.0, 808.0, 742.0, 537.0],
 [858.0, 808.0, 742.0, 538.0],
 [858.0, 808.0, 742.0, 538.0],
 [857.0, 808.0, 741.0, 537.0],
 [857.0, 808.0, 743.0, 538.0],
 [858.0, 809.0, 742.0, 537.0],
 [858.0, 808.0, 742.0, 539.0],
 [858.0, 809.0, 742.0, 538.0],
 [858.0, 809.0, 743.0, 539.0],
 [858.0, 810.0, 741.0, 539.0],
 [858.0, 809.0, 742.0, 539.0],
 [859.0, 810.0, 741.0, 539.0],
 [858.0,

In [28]:
coffee_night_mean= np.mean(coffee_night, axis=0)
print(coffee_night_mean)

[864.845 836.927 758.447 559.685]


In [29]:
air_night_mean = [876.013, 549.343, 841.496, 588.688]

In [30]:
diff_night= coffee_night_mean - air_night_mean
print(diff_night)

[-11.168 287.584 -83.049 -29.003]


In [31]:
diff = diff_day - diff_night
print(diff)

[25.854 96.718 47.735 59.626]
