In [43]:
import cbor
import matplotlib.pyplot as plt
import numpy as np
import re
import pandas as pd
import os

In [44]:
path2 = "/Users/hazelwat/Desktop/DSR/portfolio/DRS28_Hazel_n_Igor_portfolio_project/Data_for_Tests/20211202/Orange_day/"
file_name2 = "Orange.M01.cbor"
path_file2 = path2 + file_name2

f_02 = open(path_file2, 'rb')
obj = cbor.load(f_02) #dict

obj.keys()
# Out[16]: dict_keys(['protected', 'signature', 'payload'])

obj['payload']
obj['payload'].keys()
# dict_keys(['device_name', 'device_type', 'interval_ms', 'sensors', 'values'])

obj['payload']["sensors"]
# Out[22]: 
# [{'name': 'NO2', 'units': 'ppm'},
#  {'name': 'C2H5CH', 'units': 'ppm'},
#  {'name': 'VOC', 'units': 'ppm'},
#  {'name': 'CO', 'units': 'ppm'}]

d_01 = obj['payload']['values']
# Out[24]: 
# [[870.0, 542.0, 834.0, 582.0],
#  [870.0, 542.0, 834.0, 582.0],...

In [45]:
orange_day = (obj['payload']['values'])

In [46]:
orange_day

[[995.0, 945.0, 975.0, 999.0],
 [994.0, 945.0, 974.0, 999.0],
 [994.0, 946.0, 974.0, 999.0],
 [994.0, 946.0, 974.0, 999.0],
 [994.0, 946.0, 975.0, 998.0],
 [995.0, 946.0, 975.0, 999.0],
 [995.0, 946.0, 974.0, 999.0],
 [994.0, 946.0, 973.0, 999.0],
 [994.0, 946.0, 974.0, 999.0],
 [995.0, 946.0, 974.0, 999.0],
 [995.0, 946.0, 974.0, 999.0],
 [995.0, 946.0, 974.0, 999.0],
 [994.0, 946.0, 974.0, 1000.0],
 [995.0, 946.0, 973.0, 999.0],
 [995.0, 946.0, 974.0, 1000.0],
 [995.0, 946.0, 974.0, 998.0],
 [994.0, 945.0, 974.0, 999.0],
 [995.0, 947.0, 974.0, 1000.0],
 [994.0, 947.0, 973.0, 1000.0],
 [995.0, 946.0, 974.0, 998.0],
 [994.0, 946.0, 973.0, 999.0],
 [995.0, 946.0, 973.0, 1000.0],
 [995.0, 946.0, 974.0, 998.0],
 [995.0, 947.0, 974.0, 999.0],
 [994.0, 946.0, 974.0, 999.0],
 [994.0, 947.0, 974.0, 1000.0],
 [994.0, 946.0, 975.0, 999.0],
 [994.0, 947.0, 974.0, 1000.0],
 [994.0, 946.0, 974.0, 1000.0],
 [994.0, 947.0, 974.0, 999.0],
 [994.0, 946.0, 974.0, 999.0],
 [995.0, 947.0, 974.0, 998.0],


In [47]:
len(orange_day)

1000

In [48]:
orange_day_mean= np.mean(orange_day, axis=0)
print(orange_day_mean)

[994.664 952.951 973.676 999.822]


In [49]:
air_day_mean = [876.013, 549.343, 841.496, 588.688]

In [50]:
diff_day= orange_day_mean - air_day_mean
print(diff_day)

[144.0527 407.7668 158.9727 493.4968]


### Orange Night

In [51]:
path2 = "/Users/hazelwat/Desktop/DSR/portfolio/DRS28_Hazel_n_Igor_portfolio_project/Data_for_Tests/20211202/Orange_night/"
file_name2 = "Orange.N01.cbor"
path_file2 = path2 + file_name2

f_02 = open(path_file2, 'rb')
obj = cbor.load(f_02) #dict

obj.keys()
# Out[16]: dict_keys(['protected', 'signature', 'payload'])

obj['payload']
obj['payload'].keys()
# dict_keys(['device_name', 'device_type', 'interval_ms', 'sensors', 'values'])

obj['payload']["sensors"]
# Out[22]: 
# [{'name': 'NO2', 'units': 'ppm'},
#  {'name': 'C2H5CH', 'units': 'ppm'},
#  {'name': 'VOC', 'units': 'ppm'},
#  {'name': 'CO', 'units': 'ppm'}]

d_01 = obj['payload']['values']
# Out[24]: 
# [[870.0, 542.0, 834.0, 582.0],
#  [870.0, 542.0, 834.0, 582.0],...

In [52]:
orange_night = (obj['payload']['values'])

In [53]:
orange_night

[[991.0, 926.0, 968.0, 987.0],
 [990.0, 925.0, 968.0, 987.0],
 [990.0, 926.0, 967.0, 987.0],
 [991.0, 926.0, 967.0, 986.0],
 [989.0, 926.0, 967.0, 987.0],
 [991.0, 926.0, 966.0, 987.0],
 [990.0, 925.0, 967.0, 986.0],
 [991.0, 925.0, 966.0, 986.0],
 [990.0, 926.0, 968.0, 987.0],
 [991.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 988.0],
 [990.0, 926.0, 968.0, 988.0],
 [990.0, 926.0, 968.0, 988.0],
 [991.0, 926.0, 968.0, 987.0],
 [991.0, 926.0, 968.0, 988.0],
 [991.0, 926.0, 968.0, 987.0],
 [990.0, 925.0, 968.0, 988.0],
 [991.0, 926.0, 968.0, 987.0],
 [990.0, 925.0, 967.0, 987.0],
 [990.0, 926.0, 967.0, 987.0],
 [990.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 988.0],
 [991.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 988.0],
 [991.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 987.0],
 [990.0, 926.0, 968.0, 987.0],
 [991.0, 925.0, 968.0, 987.0],
 [991.0, 926.0, 967.0, 988.0],
 [991.0,

In [54]:
orange_night_mean= np.mean(orange_night, axis=0)
print(orange_night_mean)

[990.483 928.226 967.865 990.905]


In [55]:
air_night_mean = [608.995,  98.75,  390.818, 187.602]


In [56]:
diff_night= orange_day_mean - air_night_mean
print(diff_night)

[118.651 403.608 132.18  411.134]


In [57]:
diff = diff_day - diff_night
print(diff)

[25.4017  4.1588 26.7927 82.3628]
